"""empty message

Revision ID: 2bb0a7319fcd
Revises: 8c287758b0cb
Create Date: 2016-04-10 11:26:20.138261

"""

# revision identifiers, used by Alembic.
revision = '2bb0a7319fcd'
down_revision = '8c287758b0cb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_2_enabled', sa.Boolean(), nullable=False),
    sa.Column('date_2_field_label', sa.String(), nullable=False),
    sa.Column('site_visit', sa.Boolean(), nullable=False),
    sa.Column('deal_issues', sa.Boolean(), nullable=False),
    sa.Column('delete_lock_until', sa.DateTime(), nullable=True),
    sa.Column('discussion_points', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notetype')
    ### end Alembic commands ###
