"""empty message

Revision ID: 8c287758b0cb
Revises: None
Create Date: 2016-04-09 15:05:24.680156

"""

# revision identifiers, used by Alembic.
revision = '8c287758b0cb'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('site_visit_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('last_modified_by', sa.String(), nullable=True),
    sa.Column('date_2_last_modified_by', sa.String(), nullable=True),
    sa.Column('deal_issues', postgresql.JSON(), nullable=True),
    sa.Column('discussion_points', postgresql.JSON(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('date_2', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_last_modified', sa.DateTime(), nullable=True),
    sa.Column('date_2_last_modified', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('tenant')
    ### end Alembic commands ###
