"""empty message

Revision ID: a008a6d3d8a7
Revises: ccfa3553172e
Create Date: 2016-04-10 12:21:28.842017

"""

# revision identifiers, used by Alembic.
revision = 'a008a6d3d8a7'
down_revision = 'ccfa3553172e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('notetype_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'notetype', ['notetype_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'notetype_id')
    ### end Alembic commands ###
