"""empty message

Revision ID: e9e59837e6d8
Revises: 2bb0a7319fcd
Create Date: 2016-04-10 11:49:48.958751

"""

# revision identifiers, used by Alembic.
revision = 'e9e59837e6d8'
down_revision = '2bb0a7319fcd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notetype', 'date_2_field_label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notetype', 'date_2_field_label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
