"""empty message

Revision ID: cf158166f4bb
Revises: 3ef6f7a952f0
Create Date: 2016-04-06 20:56:03.221396

"""

# revision identifiers, used by Alembic.
revision = 'cf158166f4bb'
down_revision = '3ef6f7a952f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    ### end Alembic commands ###
