"""empty message

Revision ID: ff55d6df2f8a
Revises: cf158166f4bb
Create Date: 2016-04-08 16:33:56.480996

"""

# revision identifiers, used by Alembic.
revision = 'ff55d6df2f8a'
down_revision = 'cf158166f4bb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.add_column('notes', sa.Column('data', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'data')
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_all', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'results_pkey')
    )
    ### end Alembic commands ###
